# Generated by Django 3.2.13 on 2022-11-08 20:02

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('airline', models.CharField(max_length=100)),
                ('route_type', models.CharField(choices=[('non-stop', 'non-stop'), ('direct', 'direct'), ('connecting', 'connecting')], max_length=25)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('published', 'published'), ('draft', 'draft')], max_length=25)),
                ('body', tinymce.models.HTMLField()),
                ('views', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
