# Generated by Django 3.2.13 on 2022-11-24 19:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to=blog.models.upload_to),
        ),
    ]
