# Generated by Django 3.2.13 on 2022-11-30 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_images',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
